DrftServicePublicLogs/DrftServicePublicLogs/Models/Log.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DriftService.Models
{
    public class Log
    {
        public int LogID { get; set; }
        [Display(Name = "Headline")]
        public string HeadLine { get; set; }
        public string Text { get; set; }
        public bool Webb { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public string SelectedServiceType { get; set; }
    }
}

DrftServicePublicLogs/DrftServicePublicLogs/Models/ServiceType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DriftService.Models
{
    public class ServiceType
    {
        
       [Key]
        public int ServiceTypeID { get; set; }

        public string Description { get; set; }

        //public virtual ICollection<ContactServiceType> ContactServiceType { get; set; }
    }
}

DrftServicePublicLogs/DrftServicePublicLogs/Controllers/LogController.cs
using DriftService.Context;
using DriftService.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DriftService.Views.Contact
{
    public class LogController : Controller
    {
       private DriftContext db = new DriftContext();
       private List<Log> ListOfLogs = new List<Log>();

        // GET: Log
        public ActionResult Index(string searchString, string searchDate)
        {
            FindAndParserSelectedServiceType();

            List<Log> ListAfterSearch = new List<Log>();

            if (!string.IsNullOrEmpty(searchString) || (!string.IsNullOrEmpty(searchDate)))
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    foreach (var i in ListOfLogs)
                    {
                        if ((i.Text.ToLower().Contains(searchString.ToLower()) || i.HeadLine.ToLower().Contains(searchString.ToLower())) && (!ListAfterSearch.Any(x => x == i)))
                        {
                            ListAfterSearch.Add(i);
                        }
                    }
                    ListOfLogs = ListAfterSearch;
                }

                if (!string.IsNullOrEmpty(searchDate))
                {
                    DateTime SelectedDate = Convert.ToDateTime(searchDate).AddDays(1);
                    DateTime TwoWeeksBefore = SelectedDate.AddDays(-14);
                    ListOfLogs.RemoveAll(x => x.Date > SelectedDate || x.Date < TwoWeeksBefore);
                    ViewBag.SelectedDate = searchDate;
                }
                return View(ListOfLogs.OrderByDescending(o => o.Date).ToList());
            }

            else if(string.IsNullOrEmpty(searchDate))
            {
                ViewBag.SelectedDate = "Välj datum";
            }

            return View(ListOfLogs.OrderByDescending(o => o.Date).ToList().Take(50));
        }

        public ActionResult Details(int? id)
        {
            FindAndParserSelectedServiceType();
            var l = ListOfLogs.Find(x => x.LogID == id);
            ViewBag.SelectedServiceType = l.SelectedServiceType;
            return View(l);
        }

        public void FindAndParserSelectedServiceType()
        {
            string StringForParsing = "";
            List<Log> LogList = db.Logs.ToList();
            LogList.RemoveAll(x => x.Webb == false);

            foreach (var i in LogList)
            {
                string[] SplitedString = i.SelectedServiceType.Split(':');
                foreach (var ii in SplitedString)
                {
                    var s = db.ServiceTypes.ToList().Find(x => x.ServiceTypeID.ToString() == ii);
                    if (s != null)
                    {
                        if (string.IsNullOrWhiteSpace(StringForParsing))
                            StringForParsing = s.Description;
                        else
                            StringForParsing = StringForParsing + ", " + s.Description;
                    }
                }
                i.SelectedServiceType = StringForParsing;
                ListOfLogs.Add(i);
                StringForParsing = ""; 
            }
        }
    }
}

DrftServicePublicLogs/DrftServicePublicLogs/Views/Log/About.cshtml
<link rel="stylesheet" href="~/Content/StyleSheet.css" />

@{
    ViewBag.Title = "About";
}

<div class="banner">
    <div class="banner-content">
        <h2><b>About</b></h2>
    </div>
</div>








@section Scripts {
    @Scripts.Render("~/bundles/Customjquery")
    @Scripts.Render("~/bundles/jqueryval")

}

DrftServicePublicLogs/DrftServicePublicLogs/Views/Log/Details.cshtml
@model DriftService.Models.Log
<link rel="stylesheet" href="~/Content/StyleSheetContactsTable.css" />
<link rel="stylesheet" href="~/Content/StyleSheet.css" />

@{
    ViewBag.Title = "Log details";
}

<div class="banner">
    <div class="banner-content">
        <h2><b>Log details</b></h2>
    </div>
</div>


<div>
    <dl class="dl-horizontal">
        <dt>
            <br />
            @Html.DisplayNameFor(model => model.HeadLine)
        </dt>

        <dd >
            <br />
            @Html.TextAreaFor(model => model.HeadLine, new { @readonly = true, @class = "form-control TextboxSubject" })
        </dd>
      
        <dt>
            <br />
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd >
            <br />
            @Html.TextAreaFor(model => model.Text, new { @readonly = true, @class = "form-control TextboxMessage" })
        </dd>

        <dt>
            <br />
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
          <br />
          @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            <br />
            Service type
        </dt>

        <dd>
            <br />
            @ViewBag.SelectedServiceType
        </dd>

    </dl>
</div>

<div class="text-aligin-right">
    @Html.ActionLink("Back to List", "Index")
</div>
    

DrftServicePublicLogs/DrftServicePublicLogs/Views/Log/Index.cshtml
@model IEnumerable<DriftService.Models.Log>
<link rel="stylesheet" href="~/Content/StyleSheetLogsTable.css" />
<link rel="stylesheet" href="~/Content/StyleSheet.css" />

@{
    ViewBag.Title = "Driftinformation";
}

<div class="jumbotron jumbotron-fluid jumbotronFirstpage">
    <div class="container ImageCenter">
        <img src="~/Content/Images/Driftservice-Notifikation.png" alt="Driftservice-Notifikation" />
    </div>
</div>

<div>
    <h4><b>DRIFTINFORMATION</b></h4>
    <p>
        Nedan hittar du all information om eventuella störningar.
        Vill du prenumerera på driftinformation och få dem via e-post och/eller sms klicka <a href= "@System.Web.Configuration.WebConfigurationManager.AppSettings["RegistrationHttpAdress"]">här</a> för att prenumerera.
        Du kan när du vill välja att avsluta din prenumeration.
        Planerade arbeten under s.k. servicefönster hittar du här <a href="https://www.coreit.se/servicefonster">www.coreit.se/servicefonster.</a>
    </p>
</div>
<form class="form-horizontal">
   
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "searchForm" }))
    {
        <div class="form-group col-sm-9 col-lg-9">
            @Html.TextBox("SearchString", null, new { placeholder = " Sök på ord...", id = "searchString" })
            @Html.TextBox("SearchDate", null, new { placeholder = ViewBag.SelectedDate, id = "datepicker" })
            <button type="submit" value="Search" id="SearchBtn" class="glyphicon glyphicon-search btn-sm btn-default"></button>
            <span>Sök på ord och/eller datum. Datum visar 2 veckor bakåt.</span>
        </div>
    }
</form>



<div>
    <table class="table Table-border-spacing">
        <thead>
            <tr>
                <th class="th-td-padding th-first">
                   Rubrik
                </th>
                <th class="th-td-padding th-second">
                   Innehåll
                </th>
                <th class="th-td-padding th-third">
                   Datum
                </th>
                <th class="th-td-padding th-fourth">
                    <b>Tjänster</b>
                </th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr class="searchRow" onclick="document.location='@(Url.Action("Details", new { id = item.LogID }))'">
                <td class="th-td-padding td-first">
                    @(item.HeadLine.Length > 15 ? item.HeadLine.Substring(0, 25) + "..." : item.HeadLine)
                </td>
                <td class="th-td-padding td-second">
                    @(item.Text.Length > 40 ? item.Text.Substring(0, 40) + "..." : item.Text)
                </td>
                <td class="th-td-padding td-third">
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td class="th-td-padding td-fourth">
                    @(item.SelectedServiceType.Length > 40 ? item.SelectedServiceType.Substring(0, 40) + "..." : item.SelectedServiceType)
                </td>

            </tr>
        }

    </table>
</div>

DrftServicePublicLogs/DrftServicePublicLogs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Content/Images/favicon.ico" type="image/x-icon" />
    <title> @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <link rel="stylesheet" href="~/Content/StyleSheet.css" />
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Log", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Message", "Index", "Message")</li>
                    <li>@Html.ActionLink("Contacts", "Index", "Contact")</li>
                    @*<li>@Html.ActionLink("About", "About", "Log")</li>*@
                @*</ul>
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer >
            <div >
            <img style="max-width:100px;" src="~/Content/Images/LogoCore_3Color.png" alt="Driftservice-Notifikation" />
        </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>   
    @RenderSection("scripts", required: false)
</body>
</html>